Add .github
blase147/hello-microverse-project pull request #1
Opened 2022-08-18 22:17 UTC by blase147

2022-08-19 21:39 UTC, mwanawabangona requested changes
Hi <STUDENT_MENTION>,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] going through the  `readme` [template](https://github.com/microverseinc/readme-template/blob/master/README.md) for further understanding

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 21:39 UTC, mwanawabangona commented on README.md
> +- LinkedIn: [ChukwumaMosanya](www.linkedin.com/in/chukwuma-mosanya-346453)
- [ ] good so far 
- [ ] on this section that where you adding people you are saluting or who helped you through the project. 
- [ ] kindly note the you don't add the author here

2022-08-19 21:39 UTC, mwanawabangona commented on README.md
> -- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [ ] kindly note here that where you add the name of the author and there social handles.
- [ ] please make amends

2022-08-19 21:39 UTC, mwanawabangona commented on README.md
> +## Author
- [ ] Here is where you explain how the person can clone and the project on there machine. please see the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) for further understandings

2022-08-19 21:39 UTC, mwanawabangona commented on README.md
> -- Technologies used
- [ ] here you write the languages you used to build the project

2022-08-20 12:45 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 08:07 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @blase147, 




Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 16:12 UTC, merged